server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    #url: jdbc:mysql://localhost:3308/cardsdb
    url: jdbc:mysql://localhost:3306/cardsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true



info:
  app: "cards"
  description: "IdealBank cards application"
  version: "1.0.0"

logging:
  level:
    com.idealbank.cards: DEBUG